// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/aditya37/test-cc-validator/model"
	gomock "github.com/golang/mock/gomock"
)

// MockCCWriterReader is a mock of CCWriterReader interface.
type MockCCWriterReader struct {
	ctrl     *gomock.Controller
	recorder *MockCCWriterReaderMockRecorder
}

// MockCCWriterReaderMockRecorder is the mock recorder for MockCCWriterReader.
type MockCCWriterReaderMockRecorder struct {
	mock *MockCCWriterReader
}

// NewMockCCWriterReader creates a new mock instance.
func NewMockCCWriterReader(ctrl *gomock.Controller) *MockCCWriterReader {
	mock := &MockCCWriterReader{ctrl: ctrl}
	mock.recorder = &MockCCWriterReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCCWriterReader) EXPECT() *MockCCWriterReaderMockRecorder {
	return m.recorder
}

// GetCardNumber mocks base method.
func (m *MockCCWriterReader) GetCardNumber(value string) (model.MSTCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardNumber", value)
	ret0, _ := ret[0].(model.MSTCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCardNumber indicates an expected call of GetCardNumber.
func (mr *MockCCWriterReaderMockRecorder) GetCardNumber(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardNumber", reflect.TypeOf((*MockCCWriterReader)(nil).GetCardNumber), value)
}

// InsertCardNumber mocks base method.
func (m *MockCCWriterReader) InsertCardNumber(value, network string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCardNumber", value, network)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertCardNumber indicates an expected call of InsertCardNumber.
func (mr *MockCCWriterReaderMockRecorder) InsertCardNumber(value, network interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCardNumber", reflect.TypeOf((*MockCCWriterReader)(nil).InsertCardNumber), value, network)
}
